on: 
  workflow_dispatch:
  push:
    branches:
      - main
name: Testing with All Valid Inputs
jobs:
  test:
    runs-on: ubuntu-latest
    name: Testing with All Valid Inputs
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test with all inputs valid
        id: test
        uses: ammar-ahmed22/compile-typst-action@main
        with:
          source_paths: testing/file1.typ testing/file2.typ
          output_paths: myfile1.pdf myfile2.pdf
          fonts_path: testing/fonts
      # - name: Upload PDF
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: PDF
      #     path: "**/*.pdf"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: "${{ github.ref_name }}"
          file: |
            myfile1.pdf
            myfile2.pdf